// The single source of truth for every feature and its status on the site.
// Statuses were checked against the nami repository (docs/BUILD-PLAN.md, README.md and src/)
// on site.statusAsOf at site.sourceCommit. Update them here and nowhere else.
import type { Category, Feature } from "./types";

export const categories: Record<Category, { title: string; blurb: string }> = {
  protocol: {
    title: "OAuth 2.0 and OpenID Connect",
    blurb: "Standards-first flows on the OpenIddict engine, with the risky parts switched off.",
  },
  tenancy: {
    title: "Multi-tenancy",
    blurb: "Tenants are a first-class concept, isolated in the app and again in the database.",
  },
  keys: {
    title: "Keys and cryptography",
    blurb: "Signing keys that create, protect and rotate themselves.",
  },
  users: {
    title: "Users, MFA and passkeys",
    blurb: "ASP.NET Core Identity with strong authentication built in.",
  },
  federation: {
    title: "Federation and SSO",
    blurb: "Bring the identity providers your users already have.",
  },
  admin: {
    title: "Admin and governance",
    blurb: "An API and an app to run identity, with guardrails for sensitive changes.",
  },
  security: {
    title: "Security and audit",
    blurb: "Defaults that refuse unsafe configuration and evidence you can verify.",
  },
  platform: {
    title: "Platform and operations",
    blurb: "Runs anywhere .NET runs, observable from day one.",
  },
  privacy: {
    title: "Privacy and data protection",
    blurb: "Built to support GDPR and data residency requirements.",
  },
  developer: {
    title: ".NET developer experience",
    blurb: "Composes like any ASP.NET Core service you already maintain.",
  },
};

export const features = [
  // Protocol
  {
    id: "auth-code-pkce",
    title: "Authorization code with PKCE",
    summary:
      "PKCE is required for every client and only S256 is accepted. The plain method is removed, not just discouraged.",
    category: "protocol",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    specs: ["RFC 6749", "RFC 7636"],
    evidence: "src/Nami.Identity.Core/OpenIddictWiring.cs",
    highlight: true,
  },
  {
    id: "client-credentials",
    title: "Client credentials",
    summary: "Machine-to-machine tokens for services, workers and daemons, scoped per client.",
    category: "protocol",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    specs: ["RFC 6749"],
    evidence: "src/Nami.Identity.Abstractions/ClientFlow.cs",
  },
  {
    id: "refresh-rotation",
    title: "Rolling refresh tokens with reuse detection",
    summary:
      "One-time-use refresh tokens. A replayed token is detected and revoked, with a 30 second leeway for network retries and an 8 hour absolute cap.",
    category: "protocol",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    specs: ["RFC 9700"],
    evidence: "src/Nami.Identity.Core/RefreshLifetimeHandler.cs",
    highlight: true,
  },
  {
    id: "introspection-revocation",
    title: "Introspection and revocation",
    summary:
      "Token introspection and revocation endpoints, with a per-client token-bucket rate limit that answers 429 and Retry-After.",
    category: "protocol",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    specs: ["RFC 7662", "RFC 7009"],
    evidence: "src/Nami.Identity.Core/IntrospectionRateLimitWiring.cs",
  },
  {
    id: "oidc-endpoints",
    title: "Discovery, JWKS, UserInfo and end-session",
    summary: "The OpenID Connect endpoints relying parties expect, served per tenant.",
    category: "protocol",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    specs: ["OIDC Core 1.0", "OIDC Discovery 1.0"],
    evidence: "src/Nami.Identity.Core/UserInfoController.cs",
  },
  {
    id: "private-key-jwt",
    title: "private_key_jwt by default",
    summary:
      "Confidential clients authenticate with a signed assertion instead of a shared secret. Client secrets stay available when you need them.",
    category: "protocol",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    specs: ["RFC 7523"],
    evidence: "src/Nami.Identity.Abstractions/ClientAuthMethod.cs",
  },
  {
    id: "token-formats",
    title: "JWT or reference tokens, per client",
    summary:
      "Choose self-contained at+jwt access tokens or opaque reference tokens that resource servers introspect, client by client.",
    category: "protocol",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    specs: ["RFC 9068"],
    evidence: "src/Nami.Identity.Core/AccessTokenTypeHandler.cs",
  },
  {
    id: "token-encryption",
    title: "Optional access-token encryption",
    summary: "Encrypt access tokens with RSA-OAEP. RSA1_5 is refused at startup.",
    category: "protocol",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    specs: ["RFC 7516"],
    evidence: "src/Nami.Identity.Core/RsaOaepUnwrapFactory.cs",
  },
  {
    id: "consent",
    title: "Consent resolution",
    summary:
      "Every authorize request resolves to a consent decision. The cases that need no page are built; the consent screen ships with the login UI.",
    category: "protocol",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    evidence: "src/Nami.Identity.Core/ConsentResolution.cs",
  },
  {
    id: "step-up",
    title: "Step-up authentication",
    summary:
      "acr, amr and auth_time on every sign-in, mapped to NIST assurance levels, so an API can demand stronger authentication.",
    category: "protocol",
    status: "in-progress",
    horizon: "v1",
    milestone: "M2",
    phase: "04",
    specs: ["RFC 9470", "NIST SP 800-63B"],
  },
  {
    id: "backchannel-logout",
    title: "Back-channel single logout",
    summary: "Sign out once and every relying party in the session is told, server to server.",
    category: "protocol",
    status: "roadmap",
    horizon: "v1",
    milestone: "M2",
    phase: "05",
    specs: ["OIDC Back-Channel Logout 1.0"],
  },
  {
    id: "par",
    title: "Pushed authorization requests",
    summary:
      "Send authorization parameters over the back channel, required per client. The PAR endpoint is already registered.",
    category: "protocol",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "07",
    specs: ["RFC 9126"],
  },
  {
    id: "device-flow",
    title: "Device authorization flow",
    summary: "Sign in on TVs, CLIs and devices without a browser.",
    category: "protocol",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "07",
    specs: ["RFC 8628"],
  },
  {
    id: "token-exchange",
    title: "Token exchange",
    summary: "Delegation and impersonation across service chains, with act claims resolved by Nami.",
    category: "protocol",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "07",
    specs: ["RFC 8693"],
  },
  {
    id: "dpop",
    title: "DPoP sender-constrained tokens",
    summary: "Bind tokens to a client key so a stolen token is useless on its own.",
    category: "protocol",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "07",
    specs: ["RFC 9449"],
    highlight: true,
  },
  {
    id: "mtls",
    title: "Mutual TLS",
    summary: "Certificate-bound access tokens and mTLS client authentication.",
    category: "protocol",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "07",
    specs: ["RFC 8705"],
  },
  {
    id: "dcr",
    title: "Dynamic client registration",
    summary: "Standard client self-registration, planned once the protocol engine supports it.",
    category: "protocol",
    status: "roadmap",
    horizon: "later",
    milestone: "later",
    specs: ["RFC 7591"],
  },
  {
    id: "fapi2",
    title: "FAPI 2.0 security profile",
    summary: "The high-assurance profile used for open banking and financial APIs.",
    category: "protocol",
    status: "roadmap",
    horizon: "later",
    milestone: "later",
    specs: ["FAPI 2.0"],
  },

  // Tenancy
  {
    id: "pool-silo",
    title: "Pool or silo, per tenant",
    summary:
      "Run tenants in a shared database or give one its own database. Both models run the same code path.",
    category: "tenancy",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "02",
    evidence: "src/Nami.Identity.EntityFrameworkCore/NamiMultiTenantBuilderExtensions.cs",
    highlight: true,
  },
  {
    id: "per-tenant-issuer",
    title: "Per-tenant issuer",
    summary:
      "Each tenant has its own issuer and discovery document, resolved from the host name or the path.",
    category: "tenancy",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    evidence: "tests/Nami.Identity.IntegrationTests/PerTenantIssuerTests.cs",
    highlight: true,
  },
  {
    id: "row-level-security",
    title: "Row-level security backstop",
    summary:
      "Isolation is enforced in the application and again by PostgreSQL policies, tested under a role that cannot bypass them.",
    category: "tenancy",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "02",
    evidence: "tests/Nami.Identity.IntegrationTests/RowLevelSecurityBackstopTests.cs",
    highlight: true,
  },
  {
    id: "tenant-hierarchy",
    title: "Tenant hierarchy and delegated admin",
    summary: "Parent and child tenants, with admins scoped to the part of the tree they own.",
    category: "tenancy",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "06",
  },
  {
    id: "tenant-lifecycle",
    title: "Tenant provisioning and silo migration",
    summary: "Create, suspend and retire tenants, and move a tenant from the pool into its own silo.",
    category: "tenancy",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "06",
  },

  // Keys
  {
    id: "key-store",
    title: "Self-seeding key store",
    summary:
      "The first signing and encryption keys are minted at cold start and stored wrapped by ASP.NET Core Data Protection, rooted in an X.509 certificate.",
    category: "keys",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    evidence: "src/Nami.Identity.EntityFrameworkCore/DatabaseSigningKeyStore.cs",
    highlight: true,
  },
  {
    id: "signing-algorithms",
    title: "RS256 and ES256 signing",
    summary: "RSA by default, elliptic curve when you want smaller tokens. Symmetric signing keys are refused.",
    category: "keys",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    specs: ["RFC 7518"],
    evidence: "src/Nami.Identity.Keys",
  },
  {
    id: "key-rotation",
    title: "Zero-downtime key rotation",
    summary:
      "Signing keys roll over automatically with no restart, and a compromised key leaves JWKS within five minutes.",
    category: "keys",
    status: "roadmap",
    horizon: "v1",
    milestone: "M3",
    phase: "08",
    highlight: true,
  },
  {
    id: "cloud-kms",
    title: "Cloud key and secret stores",
    summary:
      "Azure Key Vault, AWS KMS and Secrets Manager, Google Cloud KMS and Secret Manager, and HashiCorp Vault behind one port.",
    category: "keys",
    status: "roadmap",
    horizon: "v1",
    milestone: "M3",
    phase: "08",
  },
  {
    id: "break-glass",
    title: "Break-glass access",
    summary: "An audited emergency path for when normal admin access is unavailable.",
    category: "keys",
    status: "roadmap",
    horizon: "v1",
    milestone: "M3",
    phase: "08",
  },
  {
    id: "fips",
    title: "FIPS 140-3 mode",
    summary: "A mode restricted to validated cryptography for regulated environments.",
    category: "keys",
    status: "roadmap",
    horizon: "later",
    milestone: "later",
  },

  // Users
  {
    id: "aspnet-identity",
    title: "ASP.NET Core Identity users",
    summary:
      "Users live in the Identity schema you know, with lockout and NIST 800-63B password rules including a breached-password check.",
    category: "users",
    status: "in-progress",
    horizon: "v1",
    milestone: "M2",
    phase: "04",
    specs: ["NIST SP 800-63B"],
  },
  {
    id: "passkeys",
    title: "Passkeys and WebAuthn",
    summary: "Phishing-resistant sign-in on the native passkey support in .NET 10.",
    category: "users",
    status: "in-progress",
    horizon: "v1",
    milestone: "M2",
    phase: "04",
    specs: ["WebAuthn"],
    highlight: true,
  },
  {
    id: "totp",
    title: "TOTP with recovery codes",
    summary: "Authenticator-app MFA with ten single-use recovery codes.",
    category: "users",
    status: "in-progress",
    horizon: "v1",
    milestone: "M2",
    phase: "04",
    specs: ["RFC 6238"],
  },
  {
    id: "sessions",
    title: "Server-side sessions",
    summary: "Sessions you can see and revoke, with idle and absolute timeouts and a concurrent-session cap.",
    category: "users",
    status: "in-progress",
    horizon: "v1",
    milestone: "M2",
    phase: "04",
  },
  {
    id: "self-service",
    title: "Self-service account flows",
    summary: "Password reset, MFA enrollment and profile changes, with email sent through a transactional outbox.",
    category: "users",
    status: "in-progress",
    horizon: "v1",
    milestone: "M2",
    phase: "04",
  },
  {
    id: "login-ui",
    title: "Themeable login, consent and logout",
    summary:
      "Server-rendered Razor pages with per-tenant logo, colors and name, localized through .resx resources.",
    category: "users",
    status: "roadmap",
    horizon: "v1",
    milestone: "M2",
    phase: "05",
  },
  {
    id: "otp-codes",
    title: "Email and SMS one-time codes",
    summary: "One-time codes for audiences that cannot use an authenticator app or passkey.",
    category: "users",
    status: "roadmap",
    horizon: "later",
    milestone: "later",
  },

  // Federation
  {
    id: "external-idp",
    title: "External identity providers",
    summary: "Sign in with Microsoft Entra ID, Google or any OpenID Connect provider.",
    category: "federation",
    status: "in-progress",
    horizon: "v1",
    milestone: "M2",
    phase: "04",
  },
  {
    id: "dynamic-federation",
    title: "Self-service federation per tenant",
    summary: "Tenants connect their own corporate identity provider without a redeploy.",
    category: "federation",
    status: "roadmap",
    horizon: "later",
    milestone: "later",
  },
  {
    id: "saml",
    title: "SAML 2.0 and WS-Federation",
    summary: "Federation with legacy enterprise applications and identity providers.",
    category: "federation",
    status: "roadmap",
    horizon: "later",
    milestone: "later",
    specs: ["SAML 2.0"],
  },
  {
    id: "kerberos",
    title: "Windows authentication",
    summary: "Kerberos and Negotiate sign-in for Active Directory environments.",
    category: "federation",
    status: "roadmap",
    horizon: "later",
    milestone: "later",
  },
  {
    id: "scim",
    title: "SCIM provisioning",
    summary: "Automated user and group provisioning from HR systems and directories.",
    category: "federation",
    status: "roadmap",
    horizon: "later",
    milestone: "later",
    specs: ["RFC 7644"],
  },

  // Admin
  {
    id: "admin-api",
    title: "Admin REST API",
    summary:
      "Applications, scopes, users, roles, tenants, sessions, branding, identity providers and audit export under /api/v1.",
    category: "admin",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "06",
    highlight: true,
  },
  {
    id: "admin-app",
    title: "Admin app",
    summary: "A server-rendered admin with an approvals inbox, change diffs and live branding preview.",
    category: "admin",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "06",
  },
  {
    id: "dual-control",
    title: "Dual-control approvals",
    summary: "Sensitive changes become proposals that a second admin must approve.",
    category: "admin",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "06",
  },
  {
    id: "authorization-engine",
    title: "Authorization engine",
    summary:
      "Role-based access through ICheckAccess, database first and swappable for a relationship-based engine. The interface is already public.",
    category: "admin",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "06",
  },

  // Security
  {
    id: "startup-gate",
    title: "Startup security gate",
    summary:
      "The server refuses to start on unsafe configuration: implicit flow, PKCE off, symmetric keys, weak encryption or plain HTTP.",
    category: "security",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    evidence: "src/Nami.Identity.Core/SecurityInvariantGate.cs",
    highlight: true,
  },
  {
    id: "audit-chain",
    title: "Tamper-evident audit log",
    summary:
      "Audit events are hash-chained, so editing or deleting a record breaks the chain and shows up in verification.",
    category: "security",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    evidence: "src/Nami.Identity.EntityFrameworkCore/HashChainAuditSink.cs",
    highlight: true,
  },
  {
    id: "security-events",
    title: "Security event stream",
    summary:
      "Token issued, token revoked, client authentication failures and replay attempts, delivered to a sink you can swap.",
    category: "security",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    evidence: "src/Nami.Identity.Core/TokenIssuedHandler.cs",
  },
  {
    id: "exact-redirects",
    title: "Exact redirect URIs",
    summary: "Redirect URIs are matched exactly. No wildcards, no partial matches.",
    category: "security",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    evidence: "src/Nami.Identity.Core/ClientSeeder.cs",
  },
  {
    id: "cors",
    title: "Per-client CORS",
    summary: "Browser origins are allowed per client, never globally.",
    category: "security",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    evidence: "src/Nami.Identity.EntityFrameworkCore/PerClientCorsPolicyProvider.cs",
  },
  {
    id: "abuse-defense",
    title: "Bot and abuse defense",
    summary:
      "Risk-triggered challenges, per-IP and per-account throttling and built-in abuse detection for sign-in.",
    category: "security",
    status: "roadmap",
    horizon: "v1",
    milestone: "M3",
  },

  // Platform
  {
    id: "postgresql",
    title: "PostgreSQL 18 on EF Core 10",
    summary: "One database engine, used deeply: row-level security, UUIDv7 keys and versioned migrations.",
    category: "platform",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "02",
    evidence: "src/Nami.Identity.EntityFrameworkCore.PostgreSQL",
  },
  {
    id: "health",
    title: "Health probes and maintenance modes",
    summary: "Liveness and readiness endpoints for orchestrators, plus a prune mode that sweeps expired tokens per tenant.",
    category: "platform",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    evidence: "src/Nami.Identity.Host/Program.cs",
  },
  {
    id: "quickstart",
    title: "Five-minute quickstart",
    summary: "docker compose up gives you a working identity provider with sample clients.",
    category: "platform",
    status: "roadmap",
    horizon: "v1",
    milestone: "M2",
    phase: "09",
  },
  {
    id: "opentelemetry",
    title: "OpenTelemetry built in",
    summary: "Traces, metrics and logs over OTLP, with dashboards for local development.",
    category: "platform",
    status: "roadmap",
    horizon: "v1",
    milestone: "M3",
    phase: "09",
  },
  {
    id: "container-helm",
    title: "Container image and Helm chart",
    summary: "A small, non-root image for amd64 and arm64, with a Helm chart for Kubernetes.",
    category: "platform",
    status: "roadmap",
    horizon: "v1",
    milestone: "M3",
    phase: "09",
  },
  {
    id: "redis-cache",
    title: "Redis acceleration that fails open",
    summary: "An optional cache layer that speeds things up and never becomes a hard dependency.",
    category: "platform",
    status: "roadmap",
    horizon: "v1",
    milestone: "M3",
  },
  {
    id: "signed-releases",
    title: "Signed, verifiable releases",
    summary: "Release signatures, SLSA provenance and a CycloneDX SBOM for every release.",
    category: "platform",
    status: "roadmap",
    horizon: "v1",
    milestone: "M3",
    phase: "09",
  },
  {
    id: "certification",
    title: "OpenID conformance",
    summary: "Run and pass the OpenID Foundation conformance suite, then apply for certification.",
    category: "platform",
    status: "roadmap",
    horizon: "v1",
    milestone: "M5",
    phase: "09",
  },

  // Privacy
  {
    id: "data-subject-rights",
    title: "Data subject rights",
    summary:
      "Access, portability, rectification, restriction and erasure that keeps the audit chain verifiable.",
    category: "privacy",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "06",
  },
  {
    id: "data-residency",
    title: "Data residency controls",
    summary: "Keep tenant data in its region, with a register of cross-border transfers.",
    category: "privacy",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
  },

  // Developer
  {
    id: "fluent-builder",
    title: "Fluent builder API",
    summary: "AddNamiIdentity() composes the server from opt-in parts in your own Program.cs.",
    category: "developer",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "01",
    evidence: "src/Nami.Identity.Core/PublicAPI.Unshipped.txt",
  },
  {
    id: "extension-points",
    title: "Swappable extension points",
    summary:
      "Replace the audit sink, security event sink, claims profile, key store or secret resolver with one call each.",
    category: "developer",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    evidence: "src/Nami.Identity.Core/PublicAPI.Unshipped.txt",
  },
  {
    id: "config-clients",
    title: "Clients and scopes as configuration",
    summary: "Declare clients and scopes in appsettings.json with secure defaults; Nami seeds them at startup.",
    category: "developer",
    status: "available",
    horizon: "v1",
    milestone: "M1",
    phase: "03",
    evidence: "src/Nami.Identity.Core/ClientSeeder.cs",
  },
  {
    id: "dotnet-template",
    title: "dotnet new template",
    summary: "dotnet new nami-identity scaffolds a host with admin, multi-tenancy, DPoP and sample clients as options.",
    category: "developer",
    status: "roadmap",
    horizon: "v1",
    milestone: "M2",
    phase: "09",
  },
  {
    id: "bff",
    title: "Backend for frontend",
    summary: "Keep tokens out of the browser: a BFF package for SPAs, with a YARP adapter.",
    category: "developer",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "06",
  },
  {
    id: "validation-package",
    title: "Resource server validation package",
    summary: "Nami.Identity.Validation for APIs, including DPoP proof checks. Plain JwtBearer works today.",
    category: "developer",
    status: "roadmap",
    horizon: "v1",
    milestone: "M4",
    phase: "07",
  },
  {
    id: "mcp-auth",
    title: "Authorization server for MCP",
    summary: "OAuth for Model Context Protocol servers and AI agents.",
    category: "developer",
    status: "roadmap",
    horizon: "later",
    milestone: "later",
  },
  {
    id: "shared-signals",
    title: "Shared Signals and CAEP",
    summary: "Real-time session and credential change events to and from other systems.",
    category: "security",
    status: "roadmap",
    horizon: "later",
    milestone: "later",
  },
  {
    id: "verifiable-credentials",
    title: "Verifiable credentials",
    summary: "Issue credentials to digital wallets with OpenID for Verifiable Credentials.",
    category: "federation",
    status: "roadmap",
    horizon: "later",
    milestone: "later",
    specs: ["OpenID4VC"],
  },
] as const satisfies readonly Feature[];

export type FeatureId = (typeof features)[number]["id"];

const byId = new Map<string, Feature>(features.map((f) => [f.id, f]));

export function getFeature(id: FeatureId): Feature {
  const feature = byId.get(id);
  if (!feature) throw new Error(`Unknown feature id: ${id}`);
  return feature;
}

/** Features the site never promotes as built: refused by design. */
export const refused = [
  { title: "Password grant", reason: "Hands user passwords to client apps. Removed from OAuth 2.1." },
  { title: "Implicit grant", reason: "Leaks tokens through the browser. The server refuses to start with it." },
  { title: "PKCE plain", reason: "Offers no protection against a code interception attacker. S256 only." },
  { title: "RSA1_5 encryption", reason: "Vulnerable to padding oracle attacks. RSA-OAEP only." },
  { title: "Symmetric signing keys", reason: "Every resource server would hold a key that can mint tokens." },
  { title: "Wildcard redirect URIs", reason: "A classic route to stolen authorization codes. Exact match only." },
] as const;
